FROM rust:latest AS builder

RUN apt-get update && apt-get install -y poppler-utils && apt-get clean && rm -r /var/lib/apt/lists/*

WORKDIR /app/backend
COPY backend/ .
RUN cargo build

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y poppler-utils ca-certificates libssl3 && apt-get clean && rm -r /var/lib/apt/lists/*

COPY --from=builder /app/backend/target/debug/minerva /usr/local/bin/
COPY backend/migrations /app/migrations

WORKDIR /app
EXPOSE 3000
CMD ["minerva"]
