FROM rust:1.82-bookworm

RUN apt-get update && apt-get install -y poppler-utils && apt-get clean && rm -r /var/lib/apt/lists/*
RUN cargo install cargo-watch

WORKDIR /app/backend
EXPOSE 3000

CMD ["cargo", "watch", "-x", "run", "-w", "crates", "-w", "migrations"]
