/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TeacherIndexRouteImport } from "./routes/teacher/index"
import { Route as CourseCourseIdRouteImport } from "./routes/course/$courseId"
import { Route as TeacherCoursesCourseIdRouteImport } from "./routes/teacher/courses.$courseId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: "/teacher/",
  path: "/teacher/",
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: "/course/$courseId",
  path: "/course/$courseId",
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCoursesCourseIdRoute = TeacherCoursesCourseIdRouteImport.update({
  id: "/teacher/courses/$courseId",
  path: "/teacher/courses/$courseId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/course/$courseId": typeof CourseCourseIdRoute
  "/teacher/": typeof TeacherIndexRoute
  "/teacher/courses/$courseId": typeof TeacherCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/course/$courseId": typeof CourseCourseIdRoute
  "/teacher": typeof TeacherIndexRoute
  "/teacher/courses/$courseId": typeof TeacherCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/course/$courseId": typeof CourseCourseIdRoute
  "/teacher/": typeof TeacherIndexRoute
  "/teacher/courses/$courseId": typeof TeacherCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/course/$courseId"
    | "/teacher/"
    | "/teacher/courses/$courseId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/course/$courseId" | "/teacher" | "/teacher/courses/$courseId"
  id:
    | "__root__"
    | "/"
    | "/course/$courseId"
    | "/teacher/"
    | "/teacher/courses/$courseId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherCoursesCourseIdRoute: typeof TeacherCoursesCourseIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/teacher/": {
      id: "/teacher/"
      path: "/teacher"
      fullPath: "/teacher/"
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/course/$courseId": {
      id: "/course/$courseId"
      path: "/course/$courseId"
      fullPath: "/course/$courseId"
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/teacher/courses/$courseId": {
      id: "/teacher/courses/$courseId"
      path: "/teacher/courses/$courseId"
      fullPath: "/teacher/courses/$courseId"
      preLoaderRoute: typeof TeacherCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherCoursesCourseIdRoute: TeacherCoursesCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
