apiVersion: v1
kind: Service
metadata:
  name: minerva-app
  namespace: minerva
spec:
  type: NodePort
  selector:
    app: minerva-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30090
