apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minerva

resources:
  - namespace.yaml
  - postgres.yaml
  - postgres-svc.yaml
  - qdrant.yaml
  - qdrant-svc.yaml
  - app.yaml
  - app-svc.yaml
  - backup.yaml
  - image-prune.yaml
