apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: minerva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: minerva-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minerva-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: minerva
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - minerva
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          hostPath:
            path: /data0/minerva/postgres
            type: DirectoryOrCreate
